// Code generated by protoc-gen-go. DO NOT EDIT.
// source: e.proto

package proto3enum

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TestEnum int32

const (
	TestEnum_FOO TestEnum = 0
)

var TestEnum_name = map[int32]string{
	0: "FOO",
}

var TestEnum_value = map[string]int32{
	"FOO": 0,
}

func (x TestEnum) String() string {
	return proto.EnumName(TestEnum_name, int32(x))
}

func (TestEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a98149bdd3263608, []int{0}
}

func init() {
	proto.RegisterEnum("proto3enum.TestEnum", TestEnum_name, TestEnum_value)
}

func init() { proto.RegisterFile("e.proto", fileDescriptor_a98149bdd3263608) }

var fileDescriptor_a98149bdd3263608 = []byte{
	// 67 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x62, 0x4f, 0xd5, 0x2b, 0x28,
	0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x02, 0x53, 0xc6, 0xa9, 0x79, 0xa5, 0xb9, 0x5a, 0xc2, 0x5c, 0x1c,
	0x21, 0xa9, 0xc5, 0x25, 0xae, 0x79, 0xa5, 0xb9, 0x42, 0xec, 0x5c, 0xcc, 0x6e, 0xfe, 0xfe, 0x02,
	0x0c, 0x49, 0x6c, 0x10, 0x05, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x20, 0x3d, 0x43, 0x3e, 0x32,
	0x00, 0x00, 0x00,
}
